#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  8 23:42:18 2018

@author: calle
"""

from Mig_Functions import *

r = np.linspace(100,0.001,2000)

#plt.figure(figsize=(10,4))
#plt.ylim(0.01, 1000)
#plt.xlim(0.1, 100)
scaling = AU**2/M_e

plt.loglog(r,sigmaG(10**(-9),0.01,r), 'r', label=r'$\dot M_g=10^{-9}$ $\rm M_{\odot}$ $\rm yr^{-1}$')
plt.loglog(r,sigmaG(10**(-8),0.01,r), 'b', label=r'$\dot M_g=10^{-8}$ $\rm M_{\odot}$ $\rm yr^{-1}$')
plt.loglog(r,sigmaG(10**(-7),0.01,r), 'g', label=r'$\dot M_g=10^{-7}$ $\rm M_{\odot}$ $\rm yr^{-1}$')
#plt.loglog(r,sigmaG(10**(-9),0.001,r), 'r', label=r'$\dot M_g=10^{-9}$ $\rm M_{\odot}$ $\rm yr^{-1}$')
#plt.loglog(r,sigmaG(10**(-8),0.001,r), 'b', label=r'$\dot M_g=10^{-8}$ $\rm M_{\odot}$ $\rm yr^{-1}$')
#plt.loglog(r,sigmaG(10**(-7),0.001,r), 'g', label=r'$\dot M_g=10^{-7}$ $\rm M_{\odot}$ $\rm yr^{-1}$')

plt.legend(fontsize='small', frameon=False, labelspacing=0.2)
plt.ylabel(r'$\Sigma_g [\rm kg/m²]$')
#plt.ylabel(r'$\Sigma_g [\rm M_E/AU²]$')
plt.xlabel(r'$r$[AU]')

plt.savefig('Sigma_alpha_0.01.png', dpi=500)